# Generated by Django 6.0.4 on 2026-04-10 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=50)),
                ("descricao", models.TextField()),
                ("nivel", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_docente",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("pagina_pessoal", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("creditos", models.IntegerField()),
                ("semestres", models.IntegerField()),
                ("formato", models.CharField(max_length=50)),
                ("website", models.URLField()),
                ("faculdade", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="AreaDeInteresse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("categoria", models.CharField(max_length=50)),
                (
                    "competencias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="areas_interesse",
                        to="portfolioPWEB.competencia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("instituicao", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=50)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("logotipo", models.ImageField(upload_to="formacoes/")),
                (
                    "competencias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="formacoes",
                        to="portfolioPWEB.competencia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("conceitos_aplicados", models.TextField()),
                ("tecnologias_resumo", models.TextField()),
                ("ano", models.IntegerField()),
                ("imagem", models.ImageField(upload_to="projetos/")),
                ("video_demo", models.URLField(blank=True, null=True)),
                ("github", models.URLField()),
                (
                    "competencias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="projetos",
                        to="portfolioPWEB.competencia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registos", models.TextField()),
                ("etapas", models.TextField()),
                ("decisoes", models.TextField()),
                ("erros_encontrados", models.TextField()),
                ("correcoes", models.TextField()),
                ("justificacao", models.TextField()),
                ("uso_ia", models.TextField()),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="makingofs",
                        to="portfolioPWEB.projeto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=50)),
                ("descricao", models.TextField()),
                ("logo", models.ImageField(upload_to="tecnologias/")),
                ("website", models.URLField()),
                ("nivel_conhecimento", models.IntegerField()),
                ("nivel_interesse", models.IntegerField()),
                (
                    "competencias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tecnologias",
                        to="portfolioPWEB.competencia",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projeto",
            name="tecnologias",
            field=models.ManyToManyField(
                blank=True, related_name="projetos", to="portfolioPWEB.tecnologia"
            ),
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("autores", models.CharField(max_length=150)),
                ("ano", models.IntegerField()),
                ("descricao", models.TextField()),
                ("link", models.URLField()),
                ("nivel_interesse", models.IntegerField()),
                (
                    "competencias",
                    models.ManyToManyField(
                        blank=True, related_name="tfcs", to="portfolioPWEB.competencia"
                    ),
                ),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tfcs",
                        to="portfolioPWEB.licenciatura",
                    ),
                ),
                (
                    "orientadores",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tfcs_orientados",
                        to="portfolioPWEB.docente",
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="tfcs", to="portfolioPWEB.tecnologia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_uc", models.CharField(max_length=30, unique=True)),
                ("nome", models.CharField(max_length=100)),
                ("ano_curricular", models.IntegerField()),
                ("creditos", models.IntegerField()),
                ("descricao", models.TextField()),
                ("imagem", models.ImageField(upload_to="ucs/")),
                ("link_uc", models.URLField()),
                (
                    "competencias",
                    models.ManyToManyField(
                        blank=True, related_name="ucs", to="portfolioPWEB.competencia"
                    ),
                ),
                (
                    "docentes",
                    models.ManyToManyField(
                        blank=True, related_name="ucs", to="portfolioPWEB.docente"
                    ),
                ),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ucs",
                        to="portfolioPWEB.licenciatura",
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="ucs", to="portfolioPWEB.tecnologia"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projeto",
            name="uc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projetos",
                to="portfolioPWEB.unidadecurricular",
            ),
        ),
    ]
