# Generated by Django 6.0.4 on 2026-04-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioPWEB", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidadecurricular",
            name="avaliacao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="metodologia",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="objetivos",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="programa",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="semestre",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="ucs/"),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="link_uc",
            field=models.URLField(blank=True),
        ),
    ]
