# Generated by Django 6.0.4 on 2026-04-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioPWEB", "0002_unidadecurricular_avaliacao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docente",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="docente",
            name="pagina_pessoal",
            field=models.URLField(blank=True),
        ),
    ]
