# Generated by Django 6.0.4 on 2026-04-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioPWEB", "0003_alter_docente_email_alter_docente_pagina_pessoal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="projetos/"),
        ),
    ]
