# Generated by Django 6.0.4 on 2026-04-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioPWEB", "0006_alter_areadeinteresse_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="video_demo",
            field=models.FileField(blank=True, null=True, upload_to="projeto/videos"),
        ),
    ]
