# Generated by Django 6.0.4 on 2026-04-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioPWEB", "0007_alter_projeto_video_demo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="video_demo",
            field=models.URLField(blank=True, null=True),
        ),
    ]
