# Generated by Django 6.0.4 on 2026-04-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioPWEB", "0008_alter_projeto_video_demo"),
    ]

    operations = [
        migrations.AddField(
            model_name="makingof",
            name="ficheiro",
            field=models.FileField(
                blank=True, null=True, upload_to="makingof/ficheiros/"
            ),
        ),
        migrations.AddField(
            model_name="makingof",
            name="imagem",
            field=models.ImageField(
                blank=True, null=True, upload_to="makingof/imagens/"
            ),
        ),
    ]
