# Generated by Django 6.0.4 on 2026-04-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioPWEB", "0009_makingof_ficheiro_makingof_imagem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="makingof",
            name="ficheiro",
        ),
        migrations.RemoveField(
            model_name="makingof",
            name="imagem",
        ),
        migrations.AlterField(
            model_name="makingof",
            name="registos",
            field=models.FileField(upload_to="makingof/registos/"),
        ),
    ]
