# Generated by Django 6.0.4 on 2026-04-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolioPWEB",
            "0010_remove_makingof_ficheiro_remove_makingof_imagem_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="makingof",
            name="registos",
            field=models.ImageField(blank=True, null=True, upload_to="makingof/"),
        ),
    ]
