# Generated by Django 6.0.4 on 2026-04-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioPWEB", "0012_alter_makingof_etapas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="titulo",
            field=models.CharField(max_length=50),
        ),
    ]
