# Generated by Django 6.0.4 on 2026-04-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioPWEB", "0013_alter_projeto_titulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="makingof",
            name="etapas",
            field=models.CharField(max_length=100),
        ),
    ]
