# Generated by Django 6.0.4 on 2026-04-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioPWEB", "0014_alter_makingof_etapas"),
    ]

    operations = [
        migrations.RenameField(
            model_name="makingof",
            old_name="registos",
            new_name="registo1",
        ),
        migrations.AddField(
            model_name="makingof",
            name="registo2",
            field=models.ImageField(blank=True, null=True, upload_to="makingof/"),
        ),
        migrations.AddField(
            model_name="makingof",
            name="registo3",
            field=models.ImageField(blank=True, null=True, upload_to="makingof/"),
        ),
    ]
