# Generated by Django 6.0.4 on 2026-04-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolioPWEB",
            "0015_rename_registos_makingof_registo1_makingof_registo2_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="licenciatura",
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="licenciaturas",
            field=models.ManyToManyField(
                blank=True,
                related_name="unidades_curriculares",
                to="portfolioPWEB.licenciatura",
            ),
        ),
    ]
