# Generated by Django 6.0.4 on 2026-04-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioPWEB", "0016_remove_unidadecurricular_licenciatura_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="makingof",
            name="registo3",
        ),
        migrations.AlterField(
            model_name="makingof",
            name="registo1",
            field=models.FileField(blank=True, null=True, upload_to="makingof/"),
        ),
        migrations.AlterField(
            model_name="makingof",
            name="registo2",
            field=models.FileField(blank=True, null=True, upload_to="makingof/"),
        ),
    ]
