# Generated by Django 6.0.4 on 2026-05-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolioPWEB",
            "0017_remove_makingof_registo3_alter_makingof_registo1_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="docente",
            name="nome",
            field=models.CharField(max_length=500),
        ),
    ]
