# Generated by Django 6.0.4 on 2026-05-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioPWEB", "0018_alter_docente_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docente",
            name="nome",
            field=models.TextField(),
        ),
    ]
